# SPDX-License-Identifier: MIT
nvkm-y += nvkm/engine/falcon.o
nvkm-y += nvkm/engine/xtensa.o

include $(srctree)/$(src)/nvkm/engine/bsp/Kbuild
include $(srctree)/$(src)/nvkm/engine/ce/Kbuild
include $(srctree)/$(src)/nvkm/engine/cipher/Kbuild
include $(srctree)/$(src)/nvkm/engine/device/Kbuild
include $(srctree)/$(src)/nvkm/engine/disp/Kbuild
include $(srctree)/$(src)/nvkm/engine/dma/Kbuild
include $(srctree)/$(src)/nvkm/engine/fifo/Kbuild
include $(srctree)/$(src)/nvkm/engine/gr/Kbuild
include $(srctree)/$(src)/nvkm/engine/mpeg/Kbuild
include $(srctree)/$(src)/nvkm/engine/msenc/Kbuild
include $(srctree)/$(src)/nvkm/engine/mspdec/Kbuild
include $(srctree)/$(src)/nvkm/engine/msppp/Kbuild
include $(srctree)/$(src)/nvkm/engine/msvld/Kbuild
include $(srctree)/$(src)/nvkm/engine/nvenc/Kbuild
include $(srctree)/$(src)/nvkm/engine/nvdec/Kbuild
include $(srctree)/$(src)/nvkm/engine/pm/Kbuild
include $(srctree)/$(src)/nvkm/engine/sec/Kbuild
include $(srctree)/$(src)/nvkm/engine/sec2/Kbuild
include $(srctree)/$(src)/nvkm/engine/sw/Kbuild
include $(srctree)/$(src)/nvkm/engine/vic/Kbuild
include $(srctree)/$(src)/nvkm/engine/vp/Kbuild
