# SPDX-License-Identifier: MIT
include $(srctree)/$(src)/nvkm/core/Kbuild
include $(srctree)/$(src)/nvkm/nvfw/Kbuild
include $(srctree)/$(src)/nvkm/falcon/Kbuild
include $(srctree)/$(src)/nvkm/subdev/Kbuild
include $(srctree)/$(src)/nvkm/engine/Kbuild
